import { Inter } from "next/font/google";
import "./reset.css"
import "./globals.css";
import "slick-carousel/slick/slick-theme.css"
import "slick-carousel/slick/slick.css"

import Nav from "@/ui/components/nav/Nav";
import Message from "@/ui/components/Message";
import NavActu from "@/ui/components/nav/NavActu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Serif+Georgian:wght@100..900&display=swap"
          rel="stylesheet"
        />
      
      </head>
      <body>
        <div className={inter.className}>
          <NavActu />
          <Nav />
          <Message />
          {children}
        </div>
      </body>
    </html>
  );
}